x-common:
  database:
    &db-env
    MYSQL_PASSWORD: &db-password "password123!"
    MYSQL_ROOT_PASSWORD: "password123!"
  panel:
    &pm-env
    APP_NAME: Paymenter
    APP_ENV: local
    APP_KEY: "base64:M2NibTF0Nzc4amhrbXFwYjlvY2o4b2Nidjdpc2tzeXI="
    APP_DEBUG: true
    APP_URL: http://localhost:8080
    LOG_CHANNEL: stack
    LOG_DEPRECATIONS_CHANNEL: null
    LOG_LEVEL: debug
    DB_CONNECTION: mysql
    DB_HOST: database
    DB_PORT: 3306
    DB_DATABASE: paymenter
    DB_USERNAME: paymenter
    BROADCAST_DRIVER: log
    CACHE_DRIVER: file
    FILESYSTEM_DISK: local
    QUEUE_CONNECTION: database
    SESSION_DRIVER: file
    SESSION_LIFETIME: 120
    MEMCACHED_HOST: cache

services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "paymenter:/var/lib/mysql"
    environment:
      <<: *db-env
      MYSQL_DATABASE: "paymenter"
      MYSQL_USER: "paymenter"
  cache:
    image: redis:alpine
    restart: always
  paymenter:
    build: .
    restart: always
    ports:
      - "8080:8080"
    links:
      - database
      - cache
    volumes:
      - "paymenter:/app/var/"
      - "paymenter:/app/storage/logs"
    environment:
      <<: *pm-env
      DB_PASSWORD: *db-password
networks:
  default:
    ipam:
      config:
        - subnet: 172.23.0.0/16
volumes:
    paymenter:
